package com.ztyj6.fs.model;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Id
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.Name
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Id
     *
     * @return the value of post.Id
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Id
     *
     * @param id the value for post.Id
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.Name
     *
     * @return the value of post.Name
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.Name
     *
     * @param name the value for post.Name
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}