package com.ztyj6.fs.model;

import java.util.Date;

public class Site {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.Id
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.Name
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.Address
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.CreateDate
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.UserId
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.CreatePurpose
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    private String createPurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.ProjectName
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    private String projectName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.Id
     *
     * @return the value of site.Id
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.Id
     *
     * @param id the value for site.Id
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.Name
     *
     * @return the value of site.Name
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.Name
     *
     * @param name the value for site.Name
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.Address
     *
     * @return the value of site.Address
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.Address
     *
     * @param address the value for site.Address
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.CreateDate
     *
     * @return the value of site.CreateDate
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.CreateDate
     *
     * @param createdate the value for site.CreateDate
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.UserId
     *
     * @return the value of site.UserId
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.UserId
     *
     * @param userid the value for site.UserId
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.CreatePurpose
     *
     * @return the value of site.CreatePurpose
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public String getCreatePurpose() {
        return createPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.CreatePurpose
     *
     * @param createpurpose the value for site.CreatePurpose
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public void setCreatePurpose(String createPurpose) {
        this.createPurpose = createPurpose == null ? null : createPurpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.ProjectName
     *
     * @return the value of site.ProjectName
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.ProjectName
     *
     * @param projectname the value for site.ProjectName
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }
}