package com.ztyj6.fs.dao;

import java.util.List;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.ztyj6.fs.model.Post;
import com.ztyj6.fs.model.Site;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int deleteByPrimaryKey(Integer id);
    void deleteBatch(List ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    Post selectByPrimaryKey(Integer id);
    List<Post> selectByPage(PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int updateByPrimaryKey(Post record);
}