package com.ztyj6.fs.dao;

import java.util.List;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.ztyj6.fs.model.Site;

public interface SiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int deleteByPrimaryKey(Integer id);
    /*
     * 批量删除站点基本信息表中的站点记录 （暂未实现）
     */
    void deleteBatch(List ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int insert(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int insertSelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    Site selectByPrimaryKey(Integer id);
    
    List<Site> selectByPage(PageBounds pageBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int updateByPrimaryKeySelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbggenerated Sat Jul 12 10:12:11 CST 2014
     */
    int updateByPrimaryKey(Site record);
}